### ISSUE TITLE
Coordinate Transformation

### ISSUE THREAD

**Issue by rylandm** [jacobbieker/Chymera#7]
Make coordinate transformation from (r',z') to (r,z/H). Equation (30) in http://iopscience.iop.org/article/10.1088/0004-637X/754/1/21/meta;jsessionid=98B0D253E344E77499E0C3D07773ECA1.c1.iopscience.cld.iop.org#apj432958s2.

**Comment by jacobbieker** [comment]
Turns out coordinate transformation is not necessary
